name: flutter_azure_tts
description: Flutter implementation of Microsoft Azure Cognitive Text-To-Speech
version: 1.0.0
homepage: https://github.com/ghuyfel/flutter_azure_tts

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  equatable: ^2.0.7
  http: ^1.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  args: ^2.7.0
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  test: ^1.26.2
  very_good_analysis: ^9.0.0
