name: flutter_azure_tts
description: Flutter implementation of Microsoft Azure Cognitive Text-To-Speech
version: 0.2.3
homepage: https://github.com/ghuyfel/flutter_azure_tts

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  equatable: ^2.0.7
  http: ^1.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  args: ^2.6.0
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0
