name: flutter_azure_tts
description: Flutter implementation of Microsoft Azure Cognitive Text-To-Speech
version: 0.1.6
homepage: https://github.com/ghuyfel/flutter_azure_tts

environment:
  sdk: ^3.0.5

dependencies:
  build_runner: ^2.4.5
  equatable: ^2.0.5
  http: ^1.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  args: ^2.4.2
  json_serializable: ^6.7.0
  test: ^1.21.1